#!/bin/sh /etc/rc.common

START=95
STOP=10
USE_PROCD=1

start_service() {
	enabled="$(uci -q get apn-autoconfig.main.autostart)"
	[ "$enabled" = "1" ] || return 0

	procd_open_instance
	procd_set_param command /usr/libexec/apn-autoconfig-boot
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_set_param term_timeout 5
	procd_close_instance
}

service_triggers() {
	procd_add_reload_trigger apn-autoconfig
}
