include $(TOPDIR)/rules.mk

PKG_NAME:=luci-app-apn-autoconfig
PKG_VERSION:=0.1.0
PKG_RELEASE:=1
PKG_LICENSE:=MIT
PKG_MAINTAINER:=DarthAnwalt

LUCI_TITLE:=LuCI support for APN Auto-Config
LUCI_DESCRIPTION:=Status, safe background actions and configuration for apn-autoconfig.
LUCI_DEPENDS:=+luci-base +apn-autoconfig
LUCI_PKGARCH:=all

include $(TOPDIR)/feeds/luci/luci.mk
