#!/bin/sh /etc/rc.common

START=90
STOP=15
USE_PROCD=1

start_service() {
	enabled="$(uci -q get apn-autoconfig-modem.main.autostart)"
	[ "$enabled" = "1" ] || return 0

	procd_open_instance
	procd_set_param command /usr/libexec/apn-autoconfig-modem-boot
	procd_set_param term_timeout 20
	procd_close_instance
}

service_triggers() {
	procd_add_reload_trigger apn-autoconfig-modem
}
